/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfacesGraficas;

import java.awt.Color;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author John
 */
public class JanelaComAbas extends javax.swing.JFrame {
    private Object label;
    private Object jTable1;

    /**
     * Creates new form JanelaComAbas
     */
    public JanelaComAbas() {
        initComponents();
        getContentPane().setBackground(new Color(94,109,252));
        setResizable(false);
        
        }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        home = new javax.swing.JPanel();
        nomeDaEscola = new javax.swing.JTextField();
        campoAzulTranslucido = new javax.swing.JLabel();
        Capa = new javax.swing.JLabel();
        editarAluno = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaAlunos = new javax.swing.JTable();
        imprimirAniversariantes = new javax.swing.JButton();
        diaInicio = new javax.swing.JTextField();
        diaFim = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        anoInicio = new javax.swing.JTextField();
        mesInicio = new javax.swing.JTextField();
        mesFim = new javax.swing.JTextField();
        anoFim = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        abaProfessores = new javax.swing.JPanel();
        abaFinanceiro = new javax.swing.JPanel();
        abaMateriais = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TextoTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabbedPane.setBackground(new java.awt.Color(153, 153, 255));

        home.setLayout(null);

        nomeDaEscola.setBackground(new java.awt.Color(0, 153, 204));
        nomeDaEscola.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        nomeDaEscola.setForeground(new java.awt.Color(255, 255, 255));
        nomeDaEscola.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nomeDaEscola.setText("   getEscola()");
        nomeDaEscola.setBorder(null);
        nomeDaEscola.setFocusable(false);
        nomeDaEscola.setOpaque(false);
        nomeDaEscola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeDaEscolaActionPerformed(evt);
            }
        });
        home.add(nomeDaEscola);
        nomeDaEscola.setBounds(-10, 0, 710, 110);

        campoAzulTranslucido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfacesGraficas/naoopaco.png"))); // NOI18N
        home.add(campoAzulTranslucido);
        campoAzulTranslucido.setBounds(-10, 0, 780, 110);

        Capa.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        Capa.setForeground(new java.awt.Color(255, 255, 255));
        Capa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfacesGraficas/Capa.jpg"))); // NOI18N
        home.add(Capa);
        Capa.setBounds(0, 0, 690, 460);

        tabbedPane.addTab("Home", home);

        editarAluno.setBackground(new java.awt.Color(153, 153, 255));
        editarAluno.setToolTipText("");

        tabelaAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Professor", "Escalação", "Aniversário"
            }
        ));
        jScrollPane1.setViewportView(tabelaAlunos);

        imprimirAniversariantes.setText("Imprimir Aniversariantes");
        imprimirAniversariantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirAniversariantesActionPerformed(evt);
            }
        });

        diaInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaInicioActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Defina o período de busca");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("(formato xx/xx/xx)");

        anoInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anoInicioActionPerformed(evt);
            }
        });

        mesInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesInicioActionPerformed(evt);
            }
        });

        jButton1.setText("botaoEdicao");

        javax.swing.GroupLayout editarAlunoLayout = new javax.swing.GroupLayout(editarAluno);
        editarAluno.setLayout(editarAlunoLayout);
        editarAlunoLayout.setHorizontalGroup(
            editarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editarAlunoLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(editarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imprimirAniversariantes, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(editarAlunoLayout.createSequentialGroup()
                        .addGroup(editarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(diaFim, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addComponent(diaInicio, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(editarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mesInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addComponent(mesFim))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(editarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(anoFim)
                            .addComponent(anoInicio)))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        editarAlunoLayout.setVerticalGroup(
            editarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(editarAlunoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(editarAlunoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diaFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anoFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(imprimirAniversariantes)
                .addGap(76, 76, 76)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Alunos", editarAluno);

        abaProfessores.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout abaProfessoresLayout = new javax.swing.GroupLayout(abaProfessores);
        abaProfessores.setLayout(abaProfessoresLayout);
        abaProfessoresLayout.setHorizontalGroup(
            abaProfessoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
        );
        abaProfessoresLayout.setVerticalGroup(
            abaProfessoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Professores", abaProfessores);

        abaFinanceiro.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout abaFinanceiroLayout = new javax.swing.GroupLayout(abaFinanceiro);
        abaFinanceiro.setLayout(abaFinanceiroLayout);
        abaFinanceiroLayout.setHorizontalGroup(
            abaFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
        );
        abaFinanceiroLayout.setVerticalGroup(
            abaFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Financeiro", abaFinanceiro);

        abaMateriais.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout abaMateriaisLayout = new javax.swing.GroupLayout(abaMateriais);
        abaMateriais.setLayout(abaMateriaisLayout);
        abaMateriaisLayout.setHorizontalGroup(
            abaMateriaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
        );
        abaMateriaisLayout.setVerticalGroup(
            abaMateriaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Materiais", abaMateriais);

        getContentPane().add(tabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 690, 487));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfacesGraficas/EscudoMenor.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 189));

        TextoTitulo.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        TextoTitulo.setForeground(new java.awt.Color(255, 255, 255));
        TextoTitulo.setText("Home");
        getContentPane().add(TextoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 21, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeDaEscolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeDaEscolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeDaEscolaActionPerformed

    private void imprimirAniversariantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirAniversariantesActionPerformed
        
    }//GEN-LAST:event_imprimirAniversariantesActionPerformed

    private void diaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diaInicioActionPerformed

    private void anoInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anoInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anoInicioActionPerformed

    private void mesInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaComAbas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaComAbas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaComAbas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaComAbas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaComAbas().setVisible(true);
                
            }
        });
    }

    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Capa;
    private javax.swing.JLabel TextoTitulo;
    private javax.swing.JPanel abaFinanceiro;
    private javax.swing.JPanel abaMateriais;
    private javax.swing.JPanel abaProfessores;
    private javax.swing.JTextField anoFim;
    private javax.swing.JTextField anoInicio;
    private javax.swing.JLabel campoAzulTranslucido;
    private javax.swing.JTextField diaFim;
    private javax.swing.JTextField diaInicio;
    private javax.swing.JPanel editarAluno;
    private javax.swing.JPanel home;
    private javax.swing.JButton imprimirAniversariantes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mesFim;
    private javax.swing.JTextField mesInicio;
    private javax.swing.JTextField nomeDaEscola;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTable tabelaAlunos;
    // End of variables declaration//GEN-END:variables
}
