/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfacesGraficas;

import ClassesHelper.CriadorPDF;
import ClassesHelper.MailSender;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import javax.mail.MessagingException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import newschoolsoccer.Aluno;
import newschoolsoccer.Escalacao;
import org.apache.commons.mail.EmailException;

/**
 *
 * @author John
 */
public class JanelaComAbas extends javax.swing.JFrame {
    private Object label;
    private Object jTable1;
    public JFrame frameForm;
    private static JanelaComAbas instancia;
    /**
     * Creates new form JanelaComAbas
     */
    public JanelaComAbas() {
        initComponents();
        getContentPane().setBackground(new Color(94,109,252));
        setResizable(false);
        int cargo = 3001;
        if(cargo > 3000)
        {
            painelComAbas.remove(2);
            painelComAbas.remove(2);
            this.criarMaterialBotao.setVisible(false);
            this.textoRemocao.setVisible(false);
            this.removerItemBotao.setVisible(false);
        }
        else
        {
            painelComAbas.remove(1);
        }
        
        }
    
    public static JanelaComAbas getInstance(){ // MÉTODO QUE VERIFICA SE A INSTANCIA JÁ ESTÁ CRIADA (SINGLETON)     
                return instancia;
        }
    
    public void atualizarTabela(Object[] linha){
        linha[0] = tabelaMateriais.getRowCount() + 1;
        ((DefaultTableModel) tabelaMateriais.getModel()).addRow(linha);
        /*incluir aqui funcao para atualizar o objeto de materiais*/
    }
    public void atualizarTabelaProfs(Object[] linha){
        linha[0] = tabelaProfessores.getRowCount() + 1;
        ((DefaultTableModel) tabelaProfessores.getModel()).addRow(linha);
        /*incluir aqui funcao para atualizar o objeto de materiais*/
    }
    public void atualizarTabelaAlunos(Object[] linha){
        
        ((DefaultTableModel) tabelaAlunos.getModel()).addRow(linha);
        /*incluir aqui funcao para atualizar o objeto de materiais*/
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        painelComAbas = new javax.swing.JTabbedPane();
        home = new javax.swing.JPanel();
        nomeDaEscola = new javax.swing.JTextField();
        campoAzulTranslucido = new javax.swing.JLabel();
        Capa = new javax.swing.JLabel();
        editarAluno = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaAlunos = new javax.swing.JTable();
        imprimirAniversariantes = new javax.swing.JButton();
        textoData = new javax.swing.JLabel();
        textoData2 = new javax.swing.JLabel();
        anoInicio = new javax.swing.JTextField();
        mesInicio = new javax.swing.JTextField();
        mesFim = new javax.swing.JTextField();
        anoFim = new javax.swing.JTextField();
        botaoEdicao = new javax.swing.JButton();
        textoData3 = new javax.swing.JLabel();
        textoData6 = new javax.swing.JLabel();
        botaoVisualizacao = new javax.swing.JButton();
        imprimirEscalacao = new javax.swing.JButton();
        nomeEscalacao = new javax.swing.JTextField();
        textoData7 = new javax.swing.JLabel();
        textoData8 = new javax.swing.JLabel();
        erroAlunos = new javax.swing.JLabel();
        botaoEdicao1 = new javax.swing.JButton();
        botaoApagarAluno = new javax.swing.JButton();
        abaProfessores = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaProfessores = new javax.swing.JTable();
        botaoCriarPerfil = new javax.swing.JButton();
        botaoVisualizarAlunosDeProf = new javax.swing.JButton();
        botaoApagarPerfil = new javax.swing.JButton();
        abaFinanceiro = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        textoData1 = new javax.swing.JLabel();
        textoData4 = new javax.swing.JLabel();
        anoInicio1 = new javax.swing.JTextField();
        mesInicio1 = new javax.swing.JTextField();
        mesFim1 = new javax.swing.JTextField();
        anoFim1 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        textoData5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        imprimirRelatorioBotao = new javax.swing.JButton();
        abaMateriais = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaMateriais = new javax.swing.JTable();
        botaoSolicitarMaterial = new javax.swing.JButton();
        textoData9 = new javax.swing.JLabel();
        textoData10 = new javax.swing.JLabel();
        textoData11 = new javax.swing.JLabel();
        textoData12 = new javax.swing.JLabel();
        criarMaterialBotao = new javax.swing.JButton();
        textoData13 = new javax.swing.JLabel();
        textoData14 = new javax.swing.JLabel();
        removerItemBotao = new javax.swing.JButton();
        textoRemocao = new javax.swing.JLabel();
        escudo = new javax.swing.JLabel();
        TextoTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("New School Soccer");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painelComAbas.setBackground(new java.awt.Color(153, 153, 255));

        home.setLayout(null);

        nomeDaEscola.setBackground(new java.awt.Color(0, 153, 204));
        nomeDaEscola.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        nomeDaEscola.setForeground(new java.awt.Color(255, 255, 255));
        nomeDaEscola.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nomeDaEscola.setText("   Bem vindo, getNome()");
        nomeDaEscola.setBorder(null);
        nomeDaEscola.setFocusable(false);
        nomeDaEscola.setOpaque(false);
        nomeDaEscola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeDaEscolaActionPerformed(evt);
            }
        });
        home.add(nomeDaEscola);
        nomeDaEscola.setBounds(-10, 0, 710, 110);

        campoAzulTranslucido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfacesGraficas/naoopaco.png"))); // NOI18N
        home.add(campoAzulTranslucido);
        campoAzulTranslucido.setBounds(-10, 0, 780, 110);

        Capa.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        Capa.setForeground(new java.awt.Color(255, 255, 255));
        Capa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfacesGraficas/Capa.jpg"))); // NOI18N
        home.add(Capa);
        Capa.setBounds(0, 0, 690, 460);

        painelComAbas.addTab("Home", home);

        editarAluno.setBackground(new java.awt.Color(153, 153, 255));
        editarAluno.setToolTipText("");

        tabelaAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Mensalidade", "Altura (cm)", "Posição", "Categoria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaAlunos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelaAlunos);
        if (tabelaAlunos.getColumnModel().getColumnCount() > 0) {
            tabelaAlunos.getColumnModel().getColumn(0).setResizable(false);
            tabelaAlunos.getColumnModel().getColumn(1).setResizable(false);
            tabelaAlunos.getColumnModel().getColumn(2).setResizable(false);
            tabelaAlunos.getColumnModel().getColumn(3).setResizable(false);
            tabelaAlunos.getColumnModel().getColumn(4).setResizable(false);
        }

        imprimirAniversariantes.setText("Imprimir Aniversariantes");
        imprimirAniversariantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirAniversariantesActionPerformed(evt);
            }
        });

        textoData.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        textoData.setForeground(new java.awt.Color(255, 255, 255));
        textoData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoData.setText("Defina o período de busca");

        textoData2.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        textoData2.setForeground(new java.awt.Color(255, 255, 255));
        textoData2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoData2.setText("(formato MM/AAAA)");

        anoInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anoInicioActionPerformed(evt);
            }
        });

        mesInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesInicioActionPerformed(evt);
            }
        });

        botaoEdicao.setText("Editar Aluno");
        botaoEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEdicaoActionPerformed(evt);
            }
        });

        textoData3.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        textoData3.setForeground(new java.awt.Color(255, 255, 255));
        textoData3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoData3.setText("Clique em um aluno para");

        textoData6.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        textoData6.setForeground(new java.awt.Color(255, 255, 255));
        textoData6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoData6.setText("visualizar/editar os dados");

        botaoVisualizacao.setText("Visualizar Aluno");
        botaoVisualizacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVisualizacaoActionPerformed(evt);
            }
        });

        imprimirEscalacao.setText("Imprimir Escalação");
        imprimirEscalacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirEscalacaoActionPerformed(evt);
            }
        });

        nomeEscalacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeEscalacaoActionPerformed(evt);
            }
        });

        textoData7.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        textoData7.setForeground(new java.awt.Color(255, 255, 255));
        textoData7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoData7.setText("Digite a categoria de");

        textoData8.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        textoData8.setForeground(new java.awt.Color(255, 255, 255));
        textoData8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoData8.setText("escalação");

        erroAlunos.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        erroAlunos.setForeground(new java.awt.Color(153, 153, 255));
        erroAlunos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        erroAlunos.setText("Valor digitado inválido!");

        botaoEdicao1.setText("Criar Aluno");
        botaoEdicao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEdicao1ActionPerformed(evt);
            }
        });

        botaoApagarAluno.setText("Apagar Aluno");
        botaoApagarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoApagarAlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editarAlunoLayout = new javax.swing.GroupLayout(editarAluno);
        editarAluno.setLayout(editarAlunoLayout);
        editarAlunoLayout.setHorizontalGroup(
            editarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editarAlunoLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoData7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nomeEscalacao)
                    .addComponent(imprimirEscalacao, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(botaoEdicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoData3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoData8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoVisualizacao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(editarAlunoLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(textoData6, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(editarAlunoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(erroAlunos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(botaoEdicao1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editarAlunoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(editarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editarAlunoLayout.createSequentialGroup()
                                .addGroup(editarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(mesInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mesFim, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(editarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(anoFim, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(anoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textoData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textoData2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(imprimirAniversariantes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(botaoApagarAluno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        editarAlunoLayout.setVerticalGroup(
            editarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(editarAlunoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(editarAlunoLayout.createSequentialGroup()
                .addComponent(textoData, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(textoData2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mesFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anoFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imprimirAniversariantes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoData3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(textoData6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(botaoVisualizacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoEdicao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoEdicao1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoApagarAluno)
                .addGap(11, 11, 11)
                .addComponent(textoData7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(textoData8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeEscalacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(imprimirEscalacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(erroAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        painelComAbas.addTab("Alunos", editarAluno);

        abaProfessores.setBackground(new java.awt.Color(153, 153, 255));

        tabelaProfessores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Professor", "Login", "Endereço", "Salário", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaProfessores.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tabelaProfessores);
        if (tabelaProfessores.getColumnModel().getColumnCount() > 0) {
            tabelaProfessores.getColumnModel().getColumn(0).setResizable(false);
            tabelaProfessores.getColumnModel().getColumn(0).setPreferredWidth(5);
            tabelaProfessores.getColumnModel().getColumn(1).setResizable(false);
            tabelaProfessores.getColumnModel().getColumn(2).setResizable(false);
            tabelaProfessores.getColumnModel().getColumn(3).setResizable(false);
            tabelaProfessores.getColumnModel().getColumn(4).setResizable(false);
            tabelaProfessores.getColumnModel().getColumn(5).setResizable(false);
        }

        botaoCriarPerfil.setText("Criar Novo Perfil");
        botaoCriarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCriarPerfilActionPerformed(evt);
            }
        });

        botaoVisualizarAlunosDeProf.setText("Visualizar Alunos");
        botaoVisualizarAlunosDeProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVisualizarAlunosDeProfActionPerformed(evt);
            }
        });

        botaoApagarPerfil.setText("Apagar Perfil");
        botaoApagarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoApagarPerfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abaProfessoresLayout = new javax.swing.GroupLayout(abaProfessores);
        abaProfessores.setLayout(abaProfessoresLayout);
        abaProfessoresLayout.setHorizontalGroup(
            abaProfessoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(abaProfessoresLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(botaoCriarPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoApagarPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(botaoVisualizarAlunosDeProf, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        abaProfessoresLayout.setVerticalGroup(
            abaProfessoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaProfessoresLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(abaProfessoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCriarPerfil)
                    .addComponent(botaoVisualizarAlunosDeProf)
                    .addComponent(botaoApagarPerfil))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE))
        );

        painelComAbas.addTab("Professores", abaProfessores);

        abaFinanceiro.setBackground(new java.awt.Color(153, 153, 255));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mês", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable4.setColumnSelectionAllowed(true);
        jTable4.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(jTable4);
        jTable4.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTable4.getColumnModel().getColumnCount() > 0) {
            jTable4.getColumnModel().getColumn(0).setResizable(false);
            jTable4.getColumnModel().getColumn(1).setResizable(false);
        }

        textoData1.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        textoData1.setForeground(new java.awt.Color(255, 255, 255));
        textoData1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoData1.setText("Defina o período de busca");

        textoData4.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        textoData4.setForeground(new java.awt.Color(255, 255, 255));
        textoData4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoData4.setText("(formato MM/AAAA)");

        anoInicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anoInicio1ActionPerformed(evt);
            }
        });

        mesInicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesInicio1ActionPerformed(evt);
            }
        });

        textoData5.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        textoData5.setForeground(new java.awt.Color(255, 255, 255));
        textoData5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoData5.setText("Total para o período especificado:");

        jButton1.setText("Pesquisar");

        imprimirRelatorioBotao.setText("Imprimir relatório");
        imprimirRelatorioBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirRelatorioBotaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abaFinanceiroLayout = new javax.swing.GroupLayout(abaFinanceiro);
        abaFinanceiro.setLayout(abaFinanceiroLayout);
        abaFinanceiroLayout.setHorizontalGroup(
            abaFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaFinanceiroLayout.createSequentialGroup()
                .addGroup(abaFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(abaFinanceiroLayout.createSequentialGroup()
                        .addComponent(textoData5, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(abaFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaFinanceiroLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(abaFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mesInicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mesFim1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(abaFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(anoInicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(anoFim1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(abaFinanceiroLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(abaFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textoData1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(textoData4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(imprimirRelatorioBotao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 43, Short.MAX_VALUE))
        );
        abaFinanceiroLayout.setVerticalGroup(
            abaFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaFinanceiroLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(textoData1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(textoData4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(abaFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anoInicio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesInicio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abaFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mesFim1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anoFim1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(29, 29, 29)
                .addComponent(imprimirRelatorioBotao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(abaFinanceiroLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(abaFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoData5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        painelComAbas.addTab("Financeiro", abaFinanceiro);

        abaMateriais.setBackground(new java.awt.Color(153, 153, 255));

        tabelaMateriais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1), "Bola",  new Integer(50),  new Integer(0)},
                { new Integer(2), "Cone",  new Integer(60),  new Integer(0)},
                { new Integer(3), "Colete",  new Integer(300),  new Integer(0)},
                { new Integer(4), "Uniforme",  new Integer(300),  new Integer(0)}
            },
            new String [] {
                "#", "Material", "Quantidade", "Solicitar novo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaMateriais.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tabelaMateriais);
        if (tabelaMateriais.getColumnModel().getColumnCount() > 0) {
            tabelaMateriais.getColumnModel().getColumn(0).setResizable(false);
            tabelaMateriais.getColumnModel().getColumn(1).setResizable(false);
            tabelaMateriais.getColumnModel().getColumn(2).setResizable(false);
            tabelaMateriais.getColumnModel().getColumn(3).setResizable(false);
        }

        botaoSolicitarMaterial.setText("Solicitar mais materiais");
        botaoSolicitarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSolicitarMaterialActionPerformed(evt);
            }
        });

        textoData9.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        textoData9.setForeground(new java.awt.Color(255, 255, 255));
        textoData9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoData9.setText("Clique para solicitar materiais");

        textoData10.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        textoData10.setForeground(new java.awt.Color(255, 255, 255));
        textoData10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoData10.setText("ao fornecedor. Somente valores");

        textoData11.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        textoData11.setForeground(new java.awt.Color(255, 255, 255));
        textoData11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoData11.setText("positivos serão considerados.");

        textoData12.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        textoData12.setForeground(new java.awt.Color(255, 255, 255));
        textoData12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoData12.setText("Valores negativos serão apenas editados");

        criarMaterialBotao.setText("Adicionar Novo Material");
        criarMaterialBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarMaterialBotaoActionPerformed(evt);
            }
        });

        textoData13.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        textoData13.setForeground(new java.awt.Color(255, 255, 255));
        textoData13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoData13.setText("e desconsiderados caso a quantidade final");

        textoData14.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        textoData14.setForeground(new java.awt.Color(255, 255, 255));
        textoData14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoData14.setText("seja menor que zero.");

        removerItemBotao.setText("Remover Material");
        removerItemBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerItemBotaoActionPerformed(evt);
            }
        });

        textoRemocao.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        textoRemocao.setForeground(new java.awt.Color(255, 255, 255));
        textoRemocao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoRemocao.setText("Selecione uma linha para excluir o material.");

        javax.swing.GroupLayout abaMateriaisLayout = new javax.swing.GroupLayout(abaMateriais);
        abaMateriais.setLayout(abaMateriaisLayout);
        abaMateriaisLayout.setHorizontalGroup(
            abaMateriaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaMateriaisLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(abaMateriaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaMateriaisLayout.createSequentialGroup()
                        .addGroup(abaMateriaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(abaMateriaisLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(removerItemBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(abaMateriaisLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(abaMateriaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botaoSolicitarMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(criarMaterialBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(abaMateriaisLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(abaMateriaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(abaMateriaisLayout.createSequentialGroup()
                                .addGroup(abaMateriaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoData12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textoData13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaMateriaisLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(textoRemocao, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(abaMateriaisLayout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(abaMateriaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(textoData9, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(abaMateriaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(abaMateriaisLayout.createSequentialGroup()
                                                    .addGap(10, 10, 10)
                                                    .addComponent(textoData11))
                                                .addComponent(textoData10)))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                            .addGroup(abaMateriaisLayout.createSequentialGroup()
                                .addComponent(textoData14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(29, 29, 29))))))
        );
        abaMateriaisLayout.setVerticalGroup(
            abaMateriaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaMateriaisLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(abaMateriaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaMateriaisLayout.createSequentialGroup()
                        .addComponent(textoData9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoData10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoData11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoData12, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoData13, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoData14, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botaoSolicitarMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(criarMaterialBotao)
                        .addGap(32, 32, 32)
                        .addComponent(textoRemocao, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removerItemBotao))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        painelComAbas.addTab("Materiais", abaMateriais);

        getContentPane().add(painelComAbas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 710, 487));

        escudo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfacesGraficas/EscudoMenor.png"))); // NOI18N
        getContentPane().add(escudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 189));

        TextoTitulo.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        TextoTitulo.setForeground(new java.awt.Color(255, 255, 255));
        TextoTitulo.setText("Escolinha Florminense");
        getContentPane().add(TextoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 21, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nomeDaEscolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeDaEscolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeDaEscolaActionPerformed

    private void mesInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesInicioActionPerformed

    private void anoInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anoInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anoInicioActionPerformed

    private void imprimirAniversariantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirAniversariantesActionPerformed
        
        Document arquivoPDF = new Document();
        try {
            PdfWriter.getInstance(arquivoPDF, new FileOutputStream("Aniversariantes.pdf"));
            arquivoPDF.open();
            
            arquivoPDF.add(Image.getInstance(String.format("src/InterfacesGraficas/EscudoMenor.png")));
            arquivoPDF.add(new Paragraph("Lista de Aniversariantes"));
            

        } catch (DocumentException | FileNotFoundException ex) {
            System.out.println("Erro! "+ex);
        } catch (IOException ex) {
            System.out.println("Erro! "+ex);
        } finally {
            arquivoPDF.close();
        }
        
        try {
            Desktop.getDesktop().open(new File("Aniversariantes.pdf"));
        } catch (IOException ex) {
            System.out.println("Erro! "+ex);
        }
    }//GEN-LAST:event_imprimirAniversariantesActionPerformed

    private void mesInicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesInicio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesInicio1ActionPerformed

    private void botaoSolicitarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSolicitarMaterialActionPerformed
        String texto = formarStringMateriais();
        if(texto.length() != 50){
            JOptionPane.showMessageDialog(null, "Pedido enviado ao fornecedor com sucesso!");
            try {
            MailSender.enviaEmailSimples(texto,"Solicitação de materiais","noreply.newschoolsoccer@gmail.com");
        } catch (EmailException ex) {
            System.out.println("Erro no envio do e-mail! "+ex.getMessage());
        }   catch (MessagingException ex) {
                System.out.println("Erro no envio do e-mail! "+ex.getMessage());
            }
        }
        


    }//GEN-LAST:event_botaoSolicitarMaterialActionPerformed

    private void imprimirEscalacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirEscalacaoActionPerformed
        String texto = "Escalação Sub-"+nomeEscalacao.getText()+"\n\n";
        int alunos = 0;
        int intEscalacao = Integer.parseInt(nomeEscalacao.getText());
        for(int i = 0; i < tabelaAlunos.getModel().getRowCount(); i++){
            if((int) tabelaAlunos.getValueAt(i, 4) == intEscalacao)
            {
                texto+="\nNome: "+tabelaAlunos.getValueAt(i, 0)+
                        "\nPosição: "+tabelaAlunos.getValueAt(i, 3);
                alunos++;
            }
        }
        if(alunos > 0)
        {
            CriadorPDF.criarPDF(texto, "Escalação "+nomeEscalacao.getText()+".pdf");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Não foram identificados alunos com este parâmetro de busca de escalação!!");
        }
        
        
        
    }//GEN-LAST:event_imprimirEscalacaoActionPerformed

    private void nomeEscalacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeEscalacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeEscalacaoActionPerformed

    private void imprimirRelatorioBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirRelatorioBotaoActionPerformed
        Document arquivoPDF = new Document();
        try {
            PdfWriter.getInstance(arquivoPDF, new FileOutputStream("Aniversariantes.pdf"));
            arquivoPDF.open();
            
            arquivoPDF.add(Image.getInstance(String.format("src/InterfacesGraficas/EscudoMenor.png")));
            arquivoPDF.add(new Paragraph("Relatório Financeiro \nPeríodo: "+mesInicio1.getText()+"/"+anoInicio1.getText()
            +" a "+mesFim1.getText()+"/"+anoInicio1.getText()));
            

        } catch (DocumentException | FileNotFoundException ex) {
            System.out.println("Erro! "+ex);
        } catch (IOException ex) {
            System.out.println("Erro! "+ex);
        } finally {
            arquivoPDF.close();
        }
        
        try {
            Desktop.getDesktop().open(new File("Aniversariantes.pdf"));
        } catch (IOException ex) {
            System.out.println("Erro! "+ex);
        }
    }//GEN-LAST:event_imprimirRelatorioBotaoActionPerformed

    private void anoInicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anoInicio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anoInicio1ActionPerformed

    private void botaoVisualizacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVisualizacaoActionPerformed
        int i = tabelaAlunos.getSelectedRow();
        if(i != -1)
        {
            ArrayList<Aluno> alunos = new ArrayList();

            String atividade = !alunos.get(i).isStatus() ? "Inativo" : "Ativo";
            String texto = "Aluno "+alunos.get(i).getNome()+
                "\nProfessor: professor.getNome()"+
                "\nCategoria: "+alunos.get(i).getCategoria()+
                "\nAltura: "+alunos.get(i).getAltura()+
                "\nStatus: "+atividade+
                "\nMensalidade: "+alunos.get(i).getMensalidade()+
                "\nData de nascimento: "+alunos.get(i).getNascimento()+
                "\n";
        
        }

        
    }//GEN-LAST:event_botaoVisualizacaoActionPerformed

    private void botaoEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEdicaoActionPerformed
        
        
        int i = tabelaAlunos.getSelectedRow();
        if(i != -1){
            try{
                if((int) tabelaAlunos.getValueAt(i, 1) < 0 ||
                    (float) tabelaAlunos.getValueAt(i, 2) < 50 ||
                    tabelaAlunos.getValueAt(i, 3) == "" ||
                    (int) tabelaAlunos.getValueAt(i, 4) < 0){
                    erroAlunos.setForeground(Color.white);
                 } else {

                JOptionPane.showMessageDialog(null, "Aluno atualizado com sucesso!");
            }
            }
            catch (NumberFormatException e){
                erroAlunos.setForeground(Color.white);
            }
            
        }
    }//GEN-LAST:event_botaoEdicaoActionPerformed

    private void criarMaterialBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarMaterialBotaoActionPerformed
        this.setEnabled(false);
        instancia = this;
        frameForm = new FrameFormulario();
        frameForm.setVisible(true);
        
        
        
    }//GEN-LAST:event_criarMaterialBotaoActionPerformed

    private void removerItemBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerItemBotaoActionPerformed
        int id = (int) tabelaMateriais.getValueAt(tabelaMateriais.getSelectedRow(),0);
        ((DefaultTableModel) tabelaMateriais.getModel()).removeRow(tabelaMateriais.getSelectedRow());
    }//GEN-LAST:event_removerItemBotaoActionPerformed

    private void botaoVisualizarAlunosDeProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVisualizarAlunosDeProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoVisualizarAlunosDeProfActionPerformed

    private void botaoCriarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCriarPerfilActionPerformed
        this.setEnabled(false);
        instancia = this;
        frameForm = new FrameIncluirProfessor(tabelaProfessores.getRowCount());
        frameForm.setVisible(true);
    }//GEN-LAST:event_botaoCriarPerfilActionPerformed

    private void botaoApagarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoApagarPerfilActionPerformed
        int id = tabelaProfessores.getSelectedRow();
        ((DefaultTableModel) tabelaProfessores.getModel()).removeRow(tabelaProfessores.getSelectedRow());
    }//GEN-LAST:event_botaoApagarPerfilActionPerformed

    private void botaoEdicao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEdicao1ActionPerformed
        this.setEnabled(false);
        instancia = this;
        frameForm = new FrameIncluirAluno();
        frameForm.setVisible(true);
    }//GEN-LAST:event_botaoEdicao1ActionPerformed

    private void botaoApagarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoApagarAlunoActionPerformed
        int id = tabelaAlunos.getSelectedRow();
        ((DefaultTableModel) tabelaAlunos.getModel()).removeRow(tabelaAlunos.getSelectedRow());
    }//GEN-LAST:event_botaoApagarAlunoActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaComAbas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaComAbas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaComAbas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaComAbas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaComAbas().setVisible(true);
                
            }
        });
    }

    
    
    public String formarStringMateriais(){
        String texto = "Prezados, \nSegue lista de materiais a solicitar: \n";
        
        for(int i = 0; i < tabelaMateriais.getRowCount() ; i++)
        {
            Object obj = tabelaMateriais.getValueAt(i,3);
            if(obj!=null){
                int addMaterial = (int) obj;
                
                if(addMaterial > 0)
                {
                    texto+= (String) tabelaMateriais.getValueAt(i,1)+": "+addMaterial+"\n";
                    
                }
                
                int novoValor = (int) tabelaMateriais.getValueAt(i, 2) + addMaterial;
                System.out.println(addMaterial);
                if(novoValor >= 0)
                {
                    tabelaMateriais.setValueAt((Object) novoValor, i, 2);
                }
                
            }
            
        }
        
        return texto;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Capa;
    private javax.swing.JLabel TextoTitulo;
    private javax.swing.JPanel abaFinanceiro;
    private javax.swing.JPanel abaMateriais;
    private javax.swing.JPanel abaProfessores;
    private javax.swing.JTextField anoFim;
    private javax.swing.JTextField anoFim1;
    private javax.swing.JTextField anoInicio;
    private javax.swing.JTextField anoInicio1;
    private javax.swing.JButton botaoApagarAluno;
    private javax.swing.JButton botaoApagarPerfil;
    private javax.swing.JButton botaoCriarPerfil;
    private javax.swing.JButton botaoEdicao;
    private javax.swing.JButton botaoEdicao1;
    private javax.swing.JButton botaoSolicitarMaterial;
    private javax.swing.JButton botaoVisualizacao;
    private javax.swing.JButton botaoVisualizarAlunosDeProf;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel campoAzulTranslucido;
    private javax.swing.JButton criarMaterialBotao;
    private javax.swing.JPanel editarAluno;
    private javax.swing.JLabel erroAlunos;
    private javax.swing.JLabel escudo;
    private javax.swing.JPanel home;
    private javax.swing.JButton imprimirAniversariantes;
    private javax.swing.JButton imprimirEscalacao;
    private javax.swing.JButton imprimirRelatorioBotao;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField mesFim;
    private javax.swing.JTextField mesFim1;
    private javax.swing.JTextField mesInicio;
    private javax.swing.JTextField mesInicio1;
    private javax.swing.JTextField nomeDaEscola;
    private javax.swing.JTextField nomeEscalacao;
    private javax.swing.JTabbedPane painelComAbas;
    private javax.swing.JButton removerItemBotao;
    private javax.swing.JTable tabelaAlunos;
    private javax.swing.JTable tabelaMateriais;
    private javax.swing.JTable tabelaProfessores;
    private javax.swing.JLabel textoData;
    private javax.swing.JLabel textoData1;
    private javax.swing.JLabel textoData10;
    private javax.swing.JLabel textoData11;
    private javax.swing.JLabel textoData12;
    private javax.swing.JLabel textoData13;
    private javax.swing.JLabel textoData14;
    private javax.swing.JLabel textoData2;
    private javax.swing.JLabel textoData3;
    private javax.swing.JLabel textoData4;
    private javax.swing.JLabel textoData5;
    private javax.swing.JLabel textoData6;
    private javax.swing.JLabel textoData7;
    private javax.swing.JLabel textoData8;
    private javax.swing.JLabel textoData9;
    private javax.swing.JLabel textoRemocao;
    // End of variables declaration//GEN-END:variables
}
