/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfacesGraficas;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Window;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.text.DefaultCaret;
/**
 *
 * @author John
 */
public class Logar extends javax.swing.JPanel {

    /**
     * Creates new form Logar
     */
    public Logar() {
        initComponents();
        campoLogin.setForeground(new Color(150, 150, 150)); 
        campoLogin.setText("Digite o seu login");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escudo = new javax.swing.JLabel();
        campoSenha = new javax.swing.JPasswordField();
        campoLogin = new javax.swing.JTextField();
        texttoLogin = new javax.swing.JLabel();
        textoSenha = new javax.swing.JLabel();
        botaoSenha = new javax.swing.JButton();
        esqueciSenha = new javax.swing.JLabel();
        senhaIncorretaMensagem = new javax.swing.JLabel();

        setBackground(new java.awt.Color(94, 109, 252));

        escudo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfacesGraficas/Escudo.png"))); // NOI18N

        campoLogin.setMinimumSize(new java.awt.Dimension(6, 25));
        campoLogin.setName(""); // NOI18N
        campoLogin.setPreferredSize(new java.awt.Dimension(6, 25));
        campoLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoLoginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoLoginFocusLost(evt);
            }
        });

        texttoLogin.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        texttoLogin.setForeground(new java.awt.Color(255, 255, 255));
        texttoLogin.setText("Login:");

        textoSenha.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        textoSenha.setForeground(new java.awt.Color(255, 255, 255));
        textoSenha.setText("Senha:");

        botaoSenha.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        botaoSenha.setText("Entrar");
        botaoSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSenhaActionPerformed(evt);
            }
        });

        esqueciSenha.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        esqueciSenha.setForeground(new java.awt.Color(255, 255, 255));
        esqueciSenha.setText("Esqueci minha senha");
        esqueciSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                esqueciSenhaMouseClicked(evt);
            }
        });

        senhaIncorretaMensagem.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        senhaIncorretaMensagem.setForeground(new java.awt.Color(255, 0, 0));
        senhaIncorretaMensagem.setText("Senha e/ou usuário incorretos, tente novamente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(escudo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(texttoLogin, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textoSenha, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(214, 214, 214))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(esqueciSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(botaoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(senhaIncorretaMensagem)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escudo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(texttoLogin)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(campoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textoSenha)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addGap(24, 24, 24)
                .addComponent(botaoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(esqueciSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(senhaIncorretaMensagem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void campoLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoLoginFocusGained
        campoLogin.setText("");
        campoLogin.setForeground(new Color(0, 0, 0));

    }//GEN-LAST:event_campoLoginFocusGained

    private void campoLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoLoginFocusLost
        if(campoLogin.getText().length() == 0)
        {
            campoLogin.setEditable(true);
            campoLogin.setForeground(new Color(150, 150, 150));
            campoLogin.setText("Digite o seu login");
        }
    }//GEN-LAST:event_campoLoginFocusLost

    private void botaoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSenhaActionPerformed
        ((Window) getRootPane().getParent()).dispose();
        JFrame novo = new JanelaComAbas();
        novo.setVisible(true);
    }//GEN-LAST:event_botaoSenhaActionPerformed

    private void esqueciSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_esqueciSenhaMouseClicked
        ((Window) getRootPane().getParent()).dispose();
         JFrame novo = new TelaLogin(new LoginInvalido());
         novo.setVisible(true);
    }//GEN-LAST:event_esqueciSenhaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSenha;
    private javax.swing.JTextField campoLogin;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JLabel escudo;
    private javax.swing.JLabel esqueciSenha;
    private javax.swing.JLabel senhaIncorretaMensagem;
    private javax.swing.JLabel textoSenha;
    private javax.swing.JLabel texttoLogin;
    // End of variables declaration//GEN-END:variables
}
