/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfacesGraficas;

import ClassesHelper.MailSender;
import java.awt.Color;
import java.awt.Window;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.JFrame;
import newschoolsoccer.Professor;
import org.apache.commons.mail.EmailException;

/**
 *
 * @author John
 */
public class LoginInvalido extends javax.swing.JPanel {

    /**
     * Creates new form LoginInvalido
     */
    public LoginInvalido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escudo = new javax.swing.JLabel();
        campoEmail = new javax.swing.JTextField();
        textoEmail = new javax.swing.JLabel();
        botaoSenha = new javax.swing.JButton();
        mensagemEmailNovaSenha = new javax.swing.JLabel();
        voltarAoLogin = new javax.swing.JLabel();
        campoLogin = new javax.swing.JTextField();
        textoLogin = new javax.swing.JLabel();

        setBackground(new java.awt.Color(94, 109, 252));

        escudo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfacesGraficas/Escudo.png"))); // NOI18N

        campoEmail.setMinimumSize(new java.awt.Dimension(6, 25));
        campoEmail.setName(""); // NOI18N
        campoEmail.setPreferredSize(new java.awt.Dimension(6, 25));
        campoEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoEmailFocusLost(evt);
            }
        });

        textoEmail.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        textoEmail.setForeground(new java.awt.Color(255, 255, 255));
        textoEmail.setText("E-mail:");

        botaoSenha.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        botaoSenha.setText("Enviar");
        botaoSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSenhaActionPerformed(evt);
            }
        });

        mensagemEmailNovaSenha.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        mensagemEmailNovaSenha.setForeground(new java.awt.Color(94, 109, 252));
        mensagemEmailNovaSenha.setText("Um e-mail será enviado com a nova senha");

        voltarAoLogin.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        voltarAoLogin.setForeground(new java.awt.Color(255, 255, 255));
        voltarAoLogin.setText("Login");
        voltarAoLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voltarAoLoginMouseClicked(evt);
            }
        });

        campoLogin.setMinimumSize(new java.awt.Dimension(6, 25));
        campoLogin.setName(""); // NOI18N
        campoLogin.setPreferredSize(new java.awt.Dimension(6, 25));
        campoLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoLoginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoLoginFocusLost(evt);
            }
        });
        campoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoLoginActionPerformed(evt);
            }
        });

        textoLogin.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        textoLogin.setForeground(new java.awt.Color(255, 255, 255));
        textoLogin.setText("Login:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botaoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(229, 229, 229))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mensagemEmailNovaSenha)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(textoEmail)
                                    .addGap(18, 18, 18)
                                    .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(textoLogin)
                                    .addGap(18, 18, 18)
                                    .addComponent(campoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(144, 144, 144))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(escudo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(voltarAoLogin)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escudo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoEmail)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoLogin)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(campoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20)
                .addComponent(botaoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mensagemEmailNovaSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(voltarAoLogin)
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void campoEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEmailFocusGained
        if(campoEmail.getText() != "")
        {
            campoEmail.setText("");
            campoEmail.setForeground(new Color(0, 0, 0));
        }

    }//GEN-LAST:event_campoEmailFocusGained

    private void campoEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEmailFocusLost
        if(campoEmail.getText().length() == 0)
        {
            campoEmail.setEditable(true);
            campoEmail.setForeground(new Color(150, 150, 150));
            campoEmail.setText("Digite o seu e-mail");
        }
    }//GEN-LAST:event_campoEmailFocusLost

    public void enviarEmailNovaSenha(){
        if(campoLogin.getText().equals("admin")){
            Professor.setPwAdemir("123");
        }else{
            Professor.setPwProf("123");
        } 
        
        try{
            
            MailSender.enviaEmailSimples("Caro usuario "+campoLogin.getText()+"\n"+
            "Sua nova senha é 123. Uma nova senha será solicitada no próximo acesso.","Troca de senha",campoEmail.getText());
        } catch(EmailException ex){
            System.out.println("Erro no envio do e-mail! "+ex.getMessage());
        } catch (MessagingException ex) {
            Logger.getLogger(LoginInvalido.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void botaoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSenhaActionPerformed
        if((campoLogin.getText().equals("admin") && campoEmail.getText().equals(Professor.getEmailAdemir()))
            || (campoLogin).getText().equals("professor") && campoEmail.getText().equals(Professor.getEmailProf())){
            enviarEmailNovaSenha();
        }
        mensagemEmailNovaSenha.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_botaoSenhaActionPerformed

    private void voltarAoLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarAoLoginMouseClicked
        ((Window) getRootPane().getParent()).dispose();
        JFrame novo = new TelaLogin(new Logar());
        novo.setVisible(true);
    }//GEN-LAST:event_voltarAoLoginMouseClicked

    private void campoLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoLoginFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_campoLoginFocusGained

    private void campoLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoLoginFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_campoLoginFocusLost

    private void campoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSenha;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoLogin;
    private javax.swing.JLabel escudo;
    private javax.swing.JLabel mensagemEmailNovaSenha;
    private javax.swing.JLabel textoEmail;
    private javax.swing.JLabel textoLogin;
    private javax.swing.JLabel voltarAoLogin;
    // End of variables declaration//GEN-END:variables
}
